http5204-aspcore-group5-r2/Models/Spiritual.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace http5204_aspcore_group5_r2.Models
{
    public class Spiritual
    {
        [Key]
        public int SpiritualID { get; set; }
        
        [Required, StringLength(255), Display(Name = "Title")]
        public string SpiritualTitle { get; set; }

        [Required, StringLength(255), Display(Name = "First Name")]
        public string SpiritualFName { get; set; }

        [Required, StringLength(255), Display(Name = "Last Name")]
        public string SpiritualLName { get; set; }

        [Required, StringLength(500), Display(Name = "Denomination")]
        public string SpiritualDenomination { get; set; }

        [Required, StringLength(500), Display(Name = "Establishment")]
        public string SpiritualEstablishment { get; set; }
        

        //will change to user ID
        [ForeignKey("AdminID")]
        public int AdminID { get; set; }

        public virtual Admin Admin { get; set; }
    }
}

http5204-aspcore-group5-r2/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using http5204_aspcore_group5_r2.Models;
using http5204_aspcore_group5_r2.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;

namespace http5204_aspcore_group5_r2.Controllers
{
    public class AdminController : Controller
    {
        private readonly NDMHCMSContext db;
        private readonly IHostingEnvironment _env;

        private readonly UserManager<ApplicationUser> _userManager;

        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public AdminController(NDMHCMSContext context, IHostingEnvironment env, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _env = env;
            _userManager = usermanager;
        }

        public async Task<int> GetUserDetails(ApplicationUser user)
        {
            //UserState:
            //0 => No account whatsoever
            //1 => Is User; Patient Online Services account
            //2 => Is an Admin account
            if (user == null) return 0; // only is a User, not an admin (i.e. Patient account only)
            var userid = user.Id;
            if (user.AdminID == null) return 1; //Only a User; not hospital staff
            else
            {
                return 2; //User has a staff/admin account and is a hospital employee

            }

        }

        // redoing GET according to Christine's example. below was the default
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public async Task<ActionResult> List(int pagenum)
        {
            var _accounts = await db.Admin.ToListAsync();
            int acctcount = _accounts.Count();
            int perpage = 3;
            int maxpage = (int)Math.Ceiling((decimal)acctcount / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pnum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }
            List<Admin> admins = await db.Admin.Skip(start).Take(perpage).ToListAsync();

            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            ViewData["UserState"] = userstate;
            ViewData["UserAdminID"] = 0;
            if (userstate==2)
            {
                ViewData["UserAdminID"] = user.AdminID;
            }
            return View(await db.Admin.ToListAsync());

            // Former process using "UserHasAdmin" token
            //if (user != null)
            //{
            //    if (user.AdminID == null) {
            //        ViewData["UserHasAdmin"] = "False";
            //    }
            //    else {
            //        ViewData["UserHasAdmin"] = user.AdminID.ToString();
            //    }
            //    return View(await db.Admin.ToListAsync());
            //}
            //else
            //{
            //    ViewData["UserHasAdmin"] = "None";
            //    return View(await db.Admin.ToListAsync());
            //}

        }

        public ActionResult Show(int id)
        {
            return RedirectToAction("Details/" + id);
        }

        // GET: Admin/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            var user = await GetCurrentUserAsync();

            if (id == null)
            {
                return new StatusCodeResult(400);
            }

            //Author located_author = await db.Authors.Include(a=>a.Blogs).SingleOrDefaultAsync(a=>a.AuthorID==id);
            Admin located_admin = await db.Admin.SingleOrDefaultAsync(a => a.AdminID == id);
            if (located_admin == null)
            {
                return NotFound();
            }
            if (user != null)
            {
                if (user.admin == located_admin)
                {
                    ViewData["UserHasAdmin"] = "True";
                }
                else
                {
                    ViewData["UserHasAdmin"] = "False";
                }
            }
            else
            {
                ViewData["UserHasAdmin"] = "False";
            }


            return View(located_admin);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("AdminID,AdminFName,AdminLName,AdminUsername")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admin.Add(admin);
                db.SaveChanges();
                var res = await MapUserToAdmin(admin);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


        // GET: Admin/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            Admin admin = db.Admin.Find(id);
            if (admin == null)
            {
                return NotFound();
            }
            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid(); 
            if (user.AdminID != id)
            {
                return Forbid();
            }
            return View(admin);
        }

        // POST: Admin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("AdminID,AdminFName,AdminLName,AdminUsername")] Admin admin)
        {
            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid();
            if (user.AdminID != admin.AdminID)
            {
                return Forbid();
            }
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admin);
        }

        // GET: Admin/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }

            var admin = await db.Admin.FindAsync(id);
            if (admin == null)
            {
                return NotFound();
            }
            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid();
            if (user.AdminID != id)
            {
                return Forbid();
            }
            return View(admin);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Admin admin = await db.Admin.FindAsync(id);
            var user = await GetCurrentUserAsync();
            if (user.AdminID != id)
            {
                return Forbid();
            }
            await UnmapUserFromAdmin(id);
            db.Admin.Remove(admin);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // unmapping/mapping functions regulating the foreign key relationships between users and admins
        
        public async Task<IActionResult> UnmapUserFromAdmin(int id)
        {
            Admin admin = await db.Admin.FindAsync(id);
            admin.user = null;
            admin.UserID = "";
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                var admin_res = await db.SaveChangesAsync();
                if (admin_res == 0)
                {
                    return BadRequest(admin_res);
                }
                else
                {
                    var user = await GetCurrentUserAsync();
                    user.admin = null;
                    user.AdminID = null;
                    var user_res = await _userManager.UpdateAsync(user);
                    if (user_res == IdentityResult.Success)
                    {
                        return Ok();
                    }
                    else
                    {
                        return BadRequest(user_res);
                    }
                }
            }
            else
            {
                return BadRequest("Unstable Model.");
            }

        }

        private async Task<IActionResult> MapUserToAdmin(Admin admin)
        {
            var user = await GetCurrentUserAsync();
            user.admin = admin;
            var user_res = await _userManager.UpdateAsync(user);
            if (user_res != IdentityResult.Success)
            {
                return BadRequest(user_res);
            }
            admin.user = user;
            admin.UserID = user.Id;
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                var admin_res = await db.SaveChangesAsync();

http5204-aspcore-group5-r2/Controllers/SpiritualController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using http5204_aspcore_group5_r2.Models;
using http5204_aspcore_group5_r2.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace http5204_aspcore_group5_r2.Controllers
{
    public class SpiritualController : Controller
    {
        private readonly NDMHCMSContext db;

        private readonly IHostingEnvironment _env;

        private readonly UserManager<ApplicationUser> _userManager;

        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public SpiritualController(NDMHCMSContext context, IHostingEnvironment env, UserManager<ApplicationUser> usermanager)
        {

            db = context;

            _env = env;

            _userManager = usermanager;
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public async Task<ActionResult> New()
        {

            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
                else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }
            }
            else
            {
                ViewData["UserHasAdmin"] = "None";
            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(string title, string fname, string lname, string denomination, string establishment)
        {
            string query = "insert into Spiritual (SpiritualTitle, SpiritualFName, SpiritualLName, SpiritualDenomination, SpiritualEstablishment) " +
                "values (@title, @fname, @lname, @denomination, @establishment)";


            SqlParameter[] myparams = new SqlParameter[5];

            myparams[0] = new SqlParameter("@title", title);

            myparams[1] = new SqlParameter("@fname", fname);

            myparams[2] = new SqlParameter("@lname", lname);

            myparams[3] = new SqlParameter("@denomination", denomination);

            myparams[4] = new SqlParameter("@establishment", establishment);


            db.Database.ExecuteSqlCommand(query, myparams);


            return RedirectToAction("List");
        }

        //pagination
        public async Task<ActionResult> List(int pagenum)
        {
            var SpiritualList = await db.Spiritual.ToListAsync();
            int reviews = SpiritualList.Count();
            int perpage = 10;
            int maxpage = (int)Math.Ceiling((decimal)reviews / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["Pagination"] = "";
            if (maxpage > 0)
            {
                ViewData["Pagination"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }

            List<Spiritual> spiritual = await db.Spiritual.Skip(start).Take(perpage).ToListAsync();

            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
                else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }
                return View(spiritual);
            }
            else
            {
                ViewData["UserHasAdmin"] = "None";
                return View(spiritual);
            }

        }

        public ActionResult Edit(int? id)
        {
            Spiritual spiritual = new Spiritual();
            spiritual =
                db.Spiritual.SingleOrDefault(p => p.SpiritualID == id);
            if (spiritual != null) return View(spiritual);
            else return NotFound();
        }

        [HttpPost]
        public ActionResult Edit(int? id, string title, string fname, string lname, string denomination, string establishment)
        {
            if ((id == null) || (db.Spiritual.Find(id) == null))
            {
                return NotFound();

            }
            string query = "update Spiritual set SpiritualTitle=@title, " +
                "SpiritualFName=@fname, " +
                "SpiritualLName=@lname," +
                "SpiritualDenomination=@denomination," +
                "SpiritualEstablishment=@establishment where SpiritualID = @id";

            SqlParameter[] myparams = new SqlParameter[6];
            myparams[0] = new SqlParameter();
            myparams[0].ParameterName = "@title";
            myparams[0].Value = title;

            myparams[1] = new SqlParameter();
            myparams[1].ParameterName = "@fname";
            myparams[1].Value = fname;

            myparams[2] = new SqlParameter();
            myparams[2].ParameterName = "@lname";
            myparams[2].Value = lname;

            myparams[3] = new SqlParameter();
            myparams[3].ParameterName = "@denomination";
            myparams[3].Value = denomination;

            myparams[4] = new SqlParameter();
            myparams[4].ParameterName = "@establishment";
            myparams[4].Value = establishment;

            myparams[5] = new SqlParameter();
            myparams[5].ParameterName = "@id";
            myparams[5].Value = id;
            db.Database.ExecuteSqlCommand(query, myparams);
 
            return RedirectToAction("List");
        }

        //Delete
        public ActionResult Delete(int id)
        {
            string sql = "delete from Spiritual where SpiritualID = @id";
            db.Database.ExecuteSqlCommand(sql, new SqlParameter("@id", id));

            return RedirectToAction("List");
        }
    }
}

http5204-aspcore-group5-r2/Views/Spiritual/Delete.cshtml
@model http5204_aspcore_group5_r2.Models.Spiritual

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

http5204-aspcore-group5-r2/Views/Spiritual/Edit.cshtml
@model http5204_aspcore_group5_r2.Models.Spiritual

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Spiritual Community Record</h2>

<div>
    @{
        switch (ViewData["UserState"])
        {
            case 0: @Url.Action("~/Spiritual/List") break;
            case 1: @Url.Action("~/Spiritual/List") break;
        }
    }
</div>

@using (Html.BeginForm("Edit", "Spiritual", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Admin</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.SpiritualID)

    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualFName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualFName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualFName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualLName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualLName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualLName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualDenomination, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualDenomination, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualDenomination, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualEstablishment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualEstablishment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualEstablishment, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

http5204-aspcore-group5-r2/Views/Spiritual/List.cshtml
@model IEnumerable<http5204_aspcore_group5_r2.Models.Spiritual>

@{
    ViewData["Title"] = "List";
}

<h2>Spiritual Leaders Affiliated with our Hospital</h2>

<p>Our hospital is committed to the provision of spiritual care. No matter what your faith or community, we will make sure that you and yours are physically and spiritually tended to.</p>

<p>As part of our mission, we have relationships with the following spiritual leaders in our community. If you would like to receive spiritual services from someone else, <b>please let us know and we will get in touch with them!</b></p>

<div>
    @{
        string id = "";
    }
    @if ((string)ViewData["UserHasAdmin"] == "False")
    {

    }
    else if ((string)ViewData["UserHasAdmin"] == "None")
    {

    }
    else
    {
        @Html.ActionLink("Add a New Spiritual Services Contact", "New", "Spiritual")

        id = (string)ViewData["UserHasAdmin"];
    }
</div>
<div>
    @{
        switch (ViewData["UserState"])
        {
            case 0: @Html.ActionLink("Register An Account", "Register", "Account") break;
            case 1: @Html.ActionLink("Create your employee admin account!", "Create", "Admin") break;
        }
    }
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SpiritualTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpiritualFName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpiritualLName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpiritualEstablishment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpiritualDenomination)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SpiritualTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpiritualFName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpiritualLName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpiritualEstablishment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpiritualDenomination)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.SpiritualID })
            @Html.Raw(" | ")
            @Html.ActionLink("Delete", "Delete", new { id = item.SpiritualID })
        </td>

    </tr>
    }

</table>

http5204-aspcore-group5-r2/Views/Spiritual/New.cshtml
@model http5204_aspcore_group5_r2.Models.Spiritual

@{
    ViewData["Title"] = "Create";
}

<h2>Add a new Religious Community Member</h2>
<div>
    @{
        switch (ViewData["UserState"])
        {
            case 0: @Html.ActionLink("Register An Account", "Register", "Account") break;
            case 1: @Html.ActionLink("Create your employee admin account!", "Create", "Admin") break;
        }
    }
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Add a New Religious Member of the Community</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualFName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualFName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualFName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualLName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualLName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualLName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualDenomination, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualDenomination, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualDenomination, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpiritualEstablishment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpiritualEstablishment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpiritualEstablishment, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>