http5204-aspcore-group5-r2/Models/Announcement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace http5204_aspcore_group5_r2.Models
{
    public class Announcement
    {
        //for Announcement ID
        [Key]
        public int AnnouncementID { get; set; }

        
        //for Announcement Profile Image(Banner Image)
        //1=>picture exists (in wwwroot/images/announcements/{id}.img)
        //0=>picture doesn't exist
        public int HasPic { get; set; }

        //accepted image file formats (jpg/jpeg/png/gif)
        public string ImgType { get; set; }

        //for Announcement Title
        [Required, StringLength(255), Display(Name = "Title")]
        public string AnnouncementTitle { get; set; }

        //for Announcement Description
        [StringLength(int.MaxValue), Display(Name = "Description")]
        public string AnnouncementDescription { get; set; }


        //for Announcement Type(Post Type)
        //Announcenment Type will have three Types: News, Media, Alert (I do not know for media and alert)
        //one News can have many Alerts 
        //see Tags in Chritine's Code
        // [ForeignKey("NewsID")]
        // public int? NewsID { get; set; }

        // public virtual News News { get; set; }


        [Required, StringLength(255), Display(Name = "Announcement Type")]
        public string AnnouncementType { get; set; }



        //for Destination URL/Link (For Ex. Learn More Link)
        [Required, StringLength(int.MaxValue), Display(Name = "Destination Link")]
        public string DestinationLink { get; set; }
        

        //for Foregin Key Admin ID (AnnouncementAdmin)
        [ForeignKey("AdminID")]
        public int AdminID { get; set; }

        public virtual Admin Admin { get; set; }
    }
}
 

http5204-aspcore-group5-r2/Controllers/AnnouncementController.cs
/*using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using http5204_aspcore_group5_r2.Models;
//using http5204_aspcore_group5_r2.Models.ViewModelMargi;
using http5204_aspcore_group5_r2.Data;*/// Extra Reference for Annoucenment Image : https://stackoverflow.com/questions/40447338/adding-images-to-asp-net-core

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using http5204_aspcore_group5_r2.Models;
using http5204_aspcore_group5_r2.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;

using Microsoft.EntityFrameworkCore; //margi added refernec: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.addasync?view=efcore-2.0

//Christine's Reference
namespace http5204_aspcore_group5_r2.Controllers
{
    public class AnnouncementController : Controller
    {
        private readonly NDMHCMSContext db;

        //margi added
        private readonly IHostingEnvironment _env; //for File's Image Path 
        private readonly UserManager<ApplicationUser> _userManager;

        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public AnnouncementController(NDMHCMSContext context, IHostingEnvironment env, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _env = env;
            _userManager = usermanager;
        }

        /* public AnnouncementController(NDMHCMSContext context)
         {
             db = context;
         }
         */


        /* public IActionResult Index()
         {
             return View();
         }*/

        public async Task<int> GetUserDetails(ApplicationUser user)
        {
            //check if the user is an Admin or not.
            //UserState
            //0 => No User
            //1 => has user has no admin
            //2 => has user has admin but no Announcements
            //3 => has user has admin and at least 1 Announcement
            if (user == null) return 0;
            var userid = user.Id;
            if (user.AdminID == null) return 1;
            else
            {
                var uadminid = user.AdminID;
                var userannouncements = await db.Announcements.Where(p => p.AdminID == uadminid).ToListAsync();
                var userannouncemnetcount = userannouncements.Count();
                if (userannouncemnetcount == 0) return 2;
                else if (userannouncemnetcount > 0) return 3;
            }
            return -1;
        }

        public async Task<bool> IsUserAnnouncementOwner(ApplicationUser user, int AnnouncementID)
        {
            if (user == null) return false;
            if (user.AdminID == null) return false;
            //purpose of this function is to check whether the user is the admin of the announcement or not
            var userposts = await
                db
                .Announcements
                .Include(p => p.Admin)
                .Where(p => p.AdminID == user.AdminID)
                .Where(p => p.AnnouncementID == AnnouncementID)
                .ToListAsync();
            if (userposts.Count() > 0) return true;
            return false;
        }


         public ActionResult Index()
         {
             return RedirectToAction("List");
         } 

        //List
        /*   public ActionResult List()
           {

               List<Announcement> announcements = db.Announcements.Include(p => p.Admin).ToList();

               return View(announcements);
           }*/

        public async Task<ActionResult> List(int pagenum)
        {
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            //tell give us context about the user
            ViewData["UserState"] = userstate;
            ViewData["UserHasAdmin"] = 0; //default 0
            if (userstate == 3)
            {
                ViewData["UserHasAdmin"] = (int)user.AdminID;
            }

            //Pagination
            var listannouncements = await db.Announcements.Include(p => p.Admin).ToListAsync();
            int announcementcount = listannouncements.Count();
            int perpage = 3;
            int maxpage = (int)Math.Ceiling((decimal)announcementcount / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }
            List<Announcement> announcements = await db.Announcements.Include(p => p.Admin).Skip(start).Take(perpage).ToListAsync();



            /* var user = await GetCurrentUserAsync();
             if (user != null)
             {
                 //if the user has no admin let the view know 
                 if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
                 //if the user has an admin then let the view know
                 else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }
                 return View(announcements);
             }
             else
             {
                 //tell the view there is no admin
                 ViewData["UserHasAdmin"] = "None";
                 return View(announcements);
             }*/
            return View(announcements);
        }

        
        
    


        public async Task<ActionResult> New()
        {
           
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
           
            switch (userstate)
            {
                case 0: return RedirectToAction("Register", "Account");
                case 1: return RedirectToAction("Create", "Admin");
            }
            
            ViewData["UserHasAdmin"] = user.AdminID;
            
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> New(string AnnouncementTitle_New, string AnnouncementDescription_New, string AnnouncementType_New, string DestinationLink_New, int AnnouncementAdmin_New)
        {
            
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);

           
            if (userstate < 2) return Forbid();
            if (user.AdminID != AnnouncementAdmin_New)
            {
               
                return Forbid();
            }

            //Raw Query   
            string query = "insert into announcements (AnnouncementTitle, AnnouncementDescription, AnnouncementType, DestinationLink, AdminID, HasPic) values (@title, @description, @type, @link, @admin, @haspic)";

            SqlParameter[] myparams = new SqlParameter[6];
            //@title paramter
            myparams[0] = new SqlParameter("@title", AnnouncementTitle_New);
            //@description parameter
            myparams[1] = new SqlParameter("@description", AnnouncementDescription_New);
            //@type parameter
            myparams[2] = new SqlParameter("@type", AnnouncementType_New);
            //@link (Destination Link) parameter
            myparams[3] = new SqlParameter("@link", DestinationLink_New);
            //@admin (id) FOREIGN KEY paramter for AnnouncementAdmin
            myparams[4] = new SqlParameter("@admin", AnnouncementAdmin_New);
            int haspic = 0;
            myparams[5] = new SqlParameter("@haspic", haspic);


            db.Database.ExecuteSqlCommand(query, myparams);

          
            return RedirectToAction("List");
        }

        //for show view

        public async Task<ActionResult> Show(int id)
        {
            /*
            if ((id == null) || (db.Announcements.Find(id) == null))
            {
                return NotFound();

            }

            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                //if the user has no author let the view know 
                if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
                //if the user has an author then let the view know
                else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }

            }

            else
            {
                //tell the view there is no user
                ViewData["UserHasAdmin"] = "None";

            }


            //Raw MSSQL query
            string query = "select * from announcements where AnnouncementID=@id";


            SqlParameter myparam = new SqlParameter("@id", id);
            */
            //margi comented this for more functionality on show page for edit and delete button*/

            if (db.Announcements.Find(id) == null)
            {
                return NotFound();

            }
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);

http5204-aspcore-group5-r2/Views/Announcement/Edit.cshtml
@model http5204_aspcore_group5_r2.Models.Announcement
@{
    // ViewData["Title"] = "Edit";
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<form method="POST" action="/Announcement/Edit/@Model.AnnouncementID" enctype="multipart/form-data">
    <!--need for image file-->
    <!--Admin ID-->
    <div>
        <input type="hidden" id="AnnouncementAdmin" name="AnnouncementAdmin" value="@Model.AdminID" />
    </div>

    <div>
        <label>Title</label>
        <input id="AnnouncementTitle" name="AnnouncementTitle" value="@Model.AnnouncementTitle" />
    </div>

    <div>
        <div>Description:</div>
        <textarea id="AnnouncementDescription" name="AnnouncementDescription">@Model.AnnouncementDescription</textarea>
    </div>

    <div>
        <div>Announcement Type: <span id="posttype">&nbsp;</span></div>
        <select id="AnnouncementType" name="AnnouncementType" onchange="SelectType(this,'posttype','AnnouncementTitle');">
            @*<option value="news">News</option>
            <option value="alert">Alert</option>
            <option value="media">Media</option>*@

            @{ IDictionary<string, string> announcementarray = new Dictionary<string, string>();
                announcementarray["News"] = "news";
                announcementarray["Alert"] = "e74c3c";
                announcementarray["Media"] = "media";


                foreach (KeyValuePair<string, string> entry in announcementarray)
                {
                    string showing = "";
                    if (entry.Value == Model.AnnouncementType)
                    {
                        showing = "selected";
                    }
                    <option value="@entry.Value" @showing>
                        @entry.Key
                    </option>
                }
            }
        </select>
    </div>

    
    <!-- To display alert in Announcement in Edit View-->
    @*<div class="alert-warning">

        </div>*@



    <div>
        <label>Destination Link:</label>
        <input id="DestinationLink" name="DestinationLink" value="@Model.DestinationLink" />
    </div>





    <!--Christine reference-->
    <div class="form-group">
        <label>Current Picture:</label>
        @if (Model.HasPic == 1)
        {

            <div class="img-container">
                <img src="~/images/Announcement/@(Model.AnnouncementID).@(Model.ImgType)" />
            </div>
        }
        else
        {
            <span>None</span>
        }
    </div>
    <div class="form-group">
        <label>Profile Picture:</label>

        <input type="file" name="announcementimg" id="announcementimg" />

    </div>

    <div>
        <input type="submit" value="Edit" />
    </div>

</form>

http5204-aspcore-group5-r2/Views/Announcement/List.cshtml
@model IEnumerable<http5204_aspcore_group5_r2.Models.Announcement>

@{
    ViewData["Title"] = "List";
}

<h2>Announcements</h2>


@*<div>
    <button>  @Html.ActionLink("Add Announcement", "New", "Announcement")</button>
</div>*@


<!--Admin can Add Announcement-->
<div>

    @{
        /*
        //UserState
            //0 => No User
            //1 => has user has no admin
            //2 => has user has admin but no faqs
            //3 => has user has admin and at least 1 faq(post)
        */

        switch (ViewData["UserState"])
        {
            //case 0: @Html.ActionLink("Sign Up!", "Register", "Account"); break;
            //case 1: @Html.ActionLink("Join Us", "Admin", "Create"); break;
            case 2:<button class="btn btn-primary">
                    @Html.ActionLink("Add Announcement", "New", "Announcement")
                </button>; break;
            case 3: <button class="btn btn-primary">
                    @Html.ActionLink("Add Announcement", "New", "Announcement")
                </button>; break;
        }

    }
</div>

<div>

    <!--Pagination-->
    @ViewData["PaginationSummary"]
    @Html.ActionLink("Prev",
        "List",
        "Announcement",
        new { pagenum= ((int)ViewData["pagenum"]-1)}
        )
    |
    @Html.ActionLink("Next",
        "List",
        "Announcement",
        new { pagenum = ((int)ViewData["pagenum"] + 1) }
        )

    @foreach (var announcement in Model)
    {
        <div class="rectangle_view">

            <div>
                

                <div class="block" style=" background-color: whitesmoke;  font-size: 20px;">

                    @if (!string.IsNullOrEmpty(announcement.AnnouncementTitle))
                    {<!--I made changes bcoz of error which shows Null or Empty Value so, here Reference: https://www.codeproject.com/Questions/1201350/Value-cannot-be-null-or-empty-in-actionlink-->

                        <label>@Html.ActionLink(announcement.AnnouncementTitle, "Show/" + announcement.AnnouncementID)</label>}

                    @*<p>@announcement.AnnouncementDescription</p>
                        <p>@announcement.AnnouncementType</p>*@

                                    @*<span>

                        <button>   @Html.ActionLink("Delete", "Delete/" + announcement.AnnouncementID) </button>

                        </span>*@
                                    @*<div>

                            @Html.ActionLink("Edit", "Edit/" + announcement.AnnouncementID)
                        </div>*@

                    <!--Margi changed for Edit and Delete button FAQ for that Admin on List Page-->
                    @if (announcement.AdminID == (int)ViewData["UserHasAdmin"])
                    {
                        <div class="del">
                            <a href="@Url.Action("Delete" , "Announcement", new { id = announcement.AnnouncementID })"><i class="far fa-trash-alt"></i></a>
                        </div>
                        <div>
                            <a href="@Url.Action("Edit" , "Announcement", new { id = announcement.AnnouncementID })"><i class="far fa-edit"></i></a>
                            @*@Html.ActionLink("Edit", "Edit/" + faq.FAQQuestionID)*@
                        </div>
                    }


                </div>

                <div class="clearfix"></div>
            </div>
        </div>

    }
</div>

http5204-aspcore-group5-r2/Views/Announcement/New.cshtml
@{
    ViewData["Title"] = "New";
}

<h2>New</h2>

<form method="POST" action="/Announcement/New">

    <!--Admin ID-->
    <div>
        <input type="hidden" id="AnnouncementAdmin_New" name="AnnouncementAdmin_New" value="@ViewData["UserHasAdmin"]" />
    </div>

    <!-- editor for a true/false value would just be a checkbox. -->
    @*<div>
            <label>Profile Picture:</label>

            <input type="file" name="announcementimg" id="announcementimg" />

        </div>*@

    <!--
    <div class="form-group">
        <label>Current Picture:</label>

    </div>
    <div class="form-group">
        <label>Profile Picture:</label>
        @*<input  type="file" name="pic" accept="images/announcements/" />*@
        <input type="file" name="announcementimg" id="announcementimg" />

    </div>
        -->


    <div>
        <label>Title</label>
        <input id="AnnouncementTitle_New" name="AnnouncementTitle_New" />
    </div>

    <div>
        <div>Description:</div>
        <textarea id="AnnouncementDescription_New" name="AnnouncementDescription_New"></textarea>
    </div>

    <div>
        <div>Announcement Type: <span id="posttype">&nbsp;</span></div>
        <select id="AnnouncementType_New" name="AnnouncementType_New" onchange="SelectType(this,'posttype','AnnouncementTitle_New');">
            <option value="news">News</option>
            @*<option value="e74c3c">Alert</option>*@ <!--value="alert"-->
            <option value="e74c3c">Alert</option>
            <option value="media">Media</option>
        </select>
    </div>

    

    <!-- To display alert in Announcement in Create View when admin select the alert value it will appear as an alert-->
    @*<div>
            <label>Alert</label>
            <select id="AnnouncementType_New" name="AnnouncementType_New">
                @foreach (var announcement in Model)
                {
                    <option value="@announcement.AnnouncementID">@announcement.AnnouncementType</option>
                }
            </select>
        </div>*@


    <div>
        <label>Destination Link:</label>
        <input id="DestinationLink_New" name="DestinationLink_New" />
    </div>

    <div>
        <input type="submit" value="Submit" />
    </div>

</form>

http5204-aspcore-group5-r2/Views/Announcement/Show.cshtml
@model http5204_aspcore_group5_r2.Models.Announcement
@{
    //ViewData["Title"] = "Show";
    ViewBag.Title = "Show";
}

<h2>Show</h2>

<!--Alert (if admin user wants to upload any Alert as an Announcement)-->
@*<h2 style="background:#@Model.AnnouncementType; color:white; padding:6px 0; text-align:center;">@Model.AnnouncementTitle</h2>*@
<h2 style="background:#@Model.AnnouncementType; color:white; padding:6px 0; text-align:center;">@Model.AnnouncementTitle</h2>

<!--More functionality-->
@{ //variable declaration id (will put user auth id into here)
    int id = 0;
}
@{
    if ((bool)ViewData["IsUserAnnouncementOwner"])
    {

        <h3>Title: @Model.AnnouncementTitle</h3>

        <p><b>Description:</b> @Model.AnnouncementDescription</p>

        <!--<p>Type: @Model.AnnouncementType</p>-->

        <p><b>Destination URL:</b> @Model.DestinationLink</p>

        <div>
            <p>Image Type: @Model.ImgType</p> 

        </div>

    }

}


<!--
<div class="bannerannouncement">
    <div class="img-container">
        @if (Model.HasPic == 1)
        {
            <div class="img-container">
                <img src="~/images/Announcement/@(Model.AnnouncementID).@(Model.ImgType)" />
            </div>
        }
        else
        {
            <img src="~/images/Announcement/default announcement image.jpg" />
        }

    </div>
    @*<span>

            @Html.ActionLink("Delete", "Delete/" + Model.AnnouncementID)

        </span>
        <div>

            @Html.ActionLink("Edit", "Edit/" + Model.AnnouncementID)
        </div>*@

</div>-->
@*<div>
        <div class="editbtn">

            <button>  @Html.ActionLink("Edit", "Edit/" + Model.AnnouncementID) </button>


        </div>
        <div class="deletebtn">

            <button> @Html.ActionLink("Delete", "Delete/" + Model.AnnouncementID)</button>
        </div>
    </div>*@




<div class="card" style="width: 630px;">
    @*<img class="card-img-top" src="..." alt="Card image cap">*@
    @*<div class="img-container">*@
    @if (Model.HasPic == 1)
    {
        <div class="card-img-top">
            <img src="~/images/Announcement/@(Model.AnnouncementID).@(Model.ImgType)" />
        </div>
    }
    else
    {
        <img src="~/images/Announcement/default announcement image.jpg" class="card-img-top" />
    }

    @*</div>*@

    <div class="card-body">
        <h4 class="card-title">@Model.AnnouncementTitle</h4>
        <p class="card-text">@Model.AnnouncementDescription</p>
        <a href="@Model.DestinationLink" class="btn btn-primary">@Model.DestinationLink</a>
    </div>
</div>



<!--Christine Blog-Show part-->

<div>
    @{ //variable declaration id (will put user auth id into here)
        // int id = 0;
    }
    @{
        if ((bool)ViewData["IsUserAnnouncementOwner"])
        {
            <div class="editbtn">
                <button>  @Html.ActionLink("Edit", "Edit", "Announcement", new { id = Model.AnnouncementID })</button> <!--for edit faq by only faq owner-->
            </div>
            <div class="deletebtn">
                <button>  @Html.ActionLink("Delete", "Delete", "Announcement", new { id = Model.AnnouncementID })</button> <!--for delete faq by only faq owner-->
            </div>
        }

    }

</div>