http5204-aspcore-group5-r2/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using http5204_aspcore_group5_r2.Models;
using http5204_aspcore_group5_r2.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;


namespace http5204_aspcore_group5_r2.Controllers
{
    public class ContactController : Controller
    {
        private readonly NDMHCMSContext db;

        private readonly IHostingEnvironment _env;

        private readonly UserManager<ApplicationUser> _userManager;

        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public ContactController(NDMHCMSContext context, IHostingEnvironment env, UserManager<ApplicationUser> usermanager)
        {

            db = context;

            _env = env;

            _userManager = usermanager;
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }


        public async Task<ActionResult> New()
        {

            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
                else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }
            }
            else
            {
                ViewData["UserHasAdmin"] = "None";
            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(string reason, string message, string name, string phone, string email)
        {
            string query = "insert into Contact (ContactReason, ContactMessage, ContactName, ContactPhone, ContactEmail) " +
                "values (@reason, @message, @name, @phone, @email)";


            SqlParameter[] myparams = new SqlParameter[5];

            myparams[0] = new SqlParameter("@reason", reason);

            myparams[1] = new SqlParameter("@message", message);

            myparams[2] = new SqlParameter("@name", name);

            myparams[3] = new SqlParameter("@phone", phone);

            myparams[4] = new SqlParameter("@email", email);


            db.Database.ExecuteSqlCommand(query, myparams);


            return RedirectToAction("List");
        }

        //pagination
        public async Task<ActionResult> List(int pagenum)
        {
            var ContactList = await db.Contact.ToListAsync();
            int reviews = ContactList.Count();
            int perpage = 10;
            int maxpage = (int)Math.Ceiling((decimal)reviews / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["Pagination"] = "";
            if (maxpage > 0)
            {
                ViewData["Pagination"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }

            List<Contact> contact = await db.Contact.Skip(start).Take(perpage).ToListAsync();

            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
                else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }
                return View(contact);
            }
            else
            {
                ViewData["UserHasAdmin"] = "None";
                return View(contact);
            }

        }

        //public ActionResult Edit(int? id)
        //{
        //    Contact contact = new Contact();
        //    contact =
        //        db.Contact.SingleOrDefault(p => p.ContactID == id);
        //    if (contact != null) return View(contact);
        //    else return NotFound();
        //}

        //[HttpPost]
        //public ActionResult Edit(int? id, string reason, string message, string name, string phone, string email)
        //{
        //    if ((id == null) || (db.Contact.Find(id) == null))
        //    {
        //        return NotFound();

        //    }
        //    string query = "update Contact set ContactReason=@reason, " +
        //        "ContactMessage=@message, " +
        //        "ContactName=@name," +
        //        "ContactPhone=@phone," +
        //        "ContactEmail=@email where ContactID = @id";

        //    SqlParameter[] myparams = new SqlParameter[6];
        //    myparams[0] = new SqlParameter();
        //    myparams[0].ParameterName = "@reason";
        //    myparams[0].Value = reason;

        //    myparams[1] = new SqlParameter();
        //    myparams[1].ParameterName = "@message";
        //    myparams[1].Value = message;

        //    myparams[2] = new SqlParameter();
        //    myparams[2].ParameterName = "@name";
        //    myparams[2].Value = name;

        //    myparams[3] = new SqlParameter();
        //    myparams[3].ParameterName = "@phone";
        //    myparams[3].Value = phone;

        //    myparams[4] = new SqlParameter();
        //    myparams[4].ParameterName = "@email";
        //    myparams[4].Value = email;

        //    myparams[5] = new SqlParameter();
        //    myparams[5].ParameterName = "@id";
        //    myparams[5].Value = id;
        //    db.Database.ExecuteSqlCommand(query, myparams);

        //    return RedirectToAction("List");
        //}

        //Delete
        public ActionResult Delete(int id)
        {
            string sql = "delete from Contact where ContactID = @id";
            db.Database.ExecuteSqlCommand(sql, new SqlParameter("@id", id));

            return RedirectToAction("List");
        }

    }
}

http5204-aspcore-group5-r2/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using http5204_aspcore_group5_r2.Models;
using http5204_aspcore_group5_r2.Data;
using System.Diagnostics;
//Christine's Reference
namespace http5204_aspcore_group5_r2.Controllers
{
    public class FAQController : Controller
    {

        private readonly NDMHCMSContext db;

        //margi added
        private readonly UserManager<ApplicationUser> _userManager;

        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public FAQController(NDMHCMSContext context, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _userManager = usermanager;
        }

        /* public IActionResult Index()
         {
             return View();
         }
         */

        public async Task<int> GetUserDetails(ApplicationUser user)
        {
            //check if the user is an Admin or not.
            //UserState
            //0 => No User
            //1 => has user has no admin
            //2 => has user has admin but no FAQs
            //3 => has user has admin and at least 1 FAQ
            if (user == null) return 0;
            var userid = user.Id;
            if (user.AdminID == null) return 1; //User has no Admin
            else
            {
                var uadminrid = user.AdminID;
                var userfaqs = await db.FAQs.Where(f => f.AdminID == uadminrid).ToListAsync();
                var userfaqcount = userfaqs.Count();
                if (userfaqcount == 0) return 2;//User has no FAQs
                else if (userfaqcount > 0) return 3; //User has atleast one FAQ
            }
            return -1;//something went wrong
        }

        public async Task<bool> IsUserFaqOwner(ApplicationUser user, int FAQQuestionID)
        {
            if (user == null) return false;
            if (user.AdminID == null) return false;
            //purpose of this function is to check whether the user is the author of the blog
            var userfaqs = await
                db
                .FAQs
                .Include(f => f.Admin)
                .Where(f => f.AdminID == user.AdminID)
                .Where(f => f.FAQQuestionID == FAQQuestionID)
                .ToListAsync();
            if (userfaqs.Count() > 0) return true;
            return false;
        }

        //Index
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        //List
        /* public ActionResult List()
         {
            List<FAQ> faqs = db.FAQs.Include(f=>f.Admin).ToList();

             return View(faqs);
         }
         */

        public async Task<ActionResult> List(int pagenum)
        {
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            //tell give us context about the user
            ViewData["UserState"] = userstate;
            ViewData["UserHasAdmin"] = 0; //default 0
            if (userstate == 3)
            {
                ViewData["UserHasAdmin"] = (int)user.AdminID;
            }


            //Pagination
            var listfaqs = await db.FAQs.Include(f => f.Admin).ToListAsync();
            int faqcount = listfaqs.Count();
            int perpage = 3;
            int maxpage = (int)Math.Ceiling((decimal)faqcount / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }
            List<FAQ> faqs = await db.FAQs.Include(f => f.Admin).Skip(start).Take(perpage).ToListAsync();



            /* var user = await GetCurrentUserAsync();

             if (user != null)
             {
                 //if the user has no Admin let the view know 
                 if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
                 //if the user has an Admin then let the view know
                 else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }
                 return View(faqs);
             }
             else
             {
                 //tell the view there is no Admin
                 ViewData["UserHasAdmin"] = "None";
                 return View(faqs);
             } 
             /*Margi changed for Edit and Delete button FAQ for that Admin on List Page*/
              
            return View(faqs);
            //GOTO Views/FAQ/List.cshtml

        }
        

        public async Task<ActionResult> New()
        {
            //DATA NEEDED
            //we need to know the context of the user
            //are they registered as an author?
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            //userstate gets the context of the user
            switch (userstate)
            {
                case 0: return RedirectToAction("Register", "Account");
                case 1: return RedirectToAction("Create", "Admin");
            }
            //The user should have an author if not 0 or 1
            ViewData["UserHasAdmin"] = user.AdminID;
            //Model defined in Models/ViewModels/BlogEdit.cs
           // BlogEdit blogeditview = new BlogEdit();

            //GOTO Views/Blog/New.cshtml
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> New(string FAQQuestionTitle_New, string FAQAnswer_New, int FAQAdmin_New)
        {
            //need to check if the author is indeed who they say they are.
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);

            //Can't make a blog if you aren't an author or don't have an account
            if (userstate < 2) return Forbid();
            if (user.AdminID != FAQAdmin_New)
            {
                //someone tried to impersonate a blog user by switching the hidden field ID
                return Forbid();
            }

            //Raw Query   
            string query = "insert into faqs (FAQQuestionTitle, FAQAnswer, AdminID) values (@title, @answer, @admin)";

            //SQL parameterized query technique
            //[SqlParameter[] myparams] => SET variable myparams as an array of type (SqlParameter)
            //[new SqlParameter[1]] => Create a new SqlParameter array with 3 items
            SqlParameter[] myparams = new SqlParameter[3];
            //for @title paramter
            myparams[0] = new SqlParameter("@title", FAQQuestionTitle_New);
            //for @answer parameter
            myparams[1] = new SqlParameter("@answer", FAQAnswer_New);
            //for @admin (id) FOREIGN KEY paramter (AdminId Foreign Key)
            myparams[2] = new SqlParameter("@admin", FAQAdmin_New);

           
            db.Database.ExecuteSqlCommand(query, myparams);

           
            return RedirectToAction("List");
        }

        public async Task<ActionResult> Edit(int id)
        {

            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            bool isValid = await IsUserFaqOwner(user, id);
            if (!isValid) return Forbid();


            var myfaq = db.FAQs.Find(id); //finds that blog
            if (myfaq != null) return View(myfaq);
            else return NotFound();
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int id, string FAQQuestionTitle, string FAQAnswer, int FAQAdmin)
        {
           
            if (db.FAQs.Find(id) == null)
            {
                return NotFound();

            }

            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            if (userstate == 3)
            {
                bool isValid = await IsUserFaqOwner(user, id);
                if (!isValid) return Forbid();
                //If Something is going to right

                //Raw Update MSSQL query
                string query = "update faqs set FAQQuestionTitle=@title, FAQAnswer=@answer, AdminID=@admin where FAQQuestionID=@id";


                SqlParameter[] myparams = new SqlParameter[4];
                //Parameter for @title "FAQQuestionTitle"
                myparams[0] = new SqlParameter("@title", FAQQuestionTitle);
                //Parameter for @answer "FAQAnswer"
                myparams[1] = new SqlParameter("@answer", FAQAnswer);
                //Parameter for (admin) id FOREIGN KEY for FAQAdmin
                myparams[2] = new SqlParameter("@admin", FAQAdmin);
                //Pararameter for (faq) id PRIMARY KEY
                myparams[3] = new SqlParameter("@id", id);

                //Execute the custom SQL command with parameters
                db.Database.ExecuteSqlCommand(query, myparams);

               
                return RedirectToAction("Show/" + id);
            }
            //if something is going to wrong
            return Forbid();

        }

        //for show view

        public async Task<ActionResult> Show(int id)
          { /*
              if ((id == null) || (db.FAQs.Find(id) == null))
              {
                  return NotFound();

              }

              var user = await GetCurrentUserAsync();

http5204-aspcore-group5-r2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using http5204_aspcore_group5_r2.Models;

namespace http5204_aspcore_group5_r2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["HomePage"] = true;
           // ViewData["NewsDisplay"] = true;
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

http5204-aspcore-group5-r2/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

http5204-aspcore-group5-r2/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

http5204-aspcore-group5-r2/Views/Home/Index.cshtml
@model http5204_aspcore_group5_r2.Models.NewsAndUpdate
@{
    ViewData["Title"] = "Home";
}
<!-- page -wrapper starts here-->
<div class="page-wrapper">
    <!-- main starts here-->
    <main class="main">
        <div class="image-slider">
            <!--image slider starts here-->
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="~/images/siteImages/womeneye.jpg" class="d-block w-100" alt="hospital image" />
                    </div>
                    <div class="carousel-item">
                        <img src="~/images/siteImages/stethoscopeBW.jpg" class="d-block w-100" alt="hosital view">
                    </div>
                    <div class="carousel-item">
                        <img src="~/images/siteImages/holdinghand.jpg" class="d-block w-100" alt="hospital image">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <!-- image silder ends here-->
        </div>
        <div class="easy-link">
            <div classs="easy-link-container">
                <div class="col-link">
                    <div class="doctors  bg-primary-blue center ">
                        <a asp-area="" asp-controller="" asp-action="" style="color:black;">
                         <i class="fas fa-user fa-3x "></i>
                            </a>
                        <h4 class="center">
                            <a asp-area="" asp-controller="" asp-action="">Doctors</a>
                        </h4>
                    </div>
                    <div class="book-app  bg-primary-blue center">
                        <a asp-area="" asp-controller="Appointments" asp-action="Create" style="color:black;">
                            <i class="far fa-calendar-check center fa-3x"></i>
                        </a>
                            <h4 class="center">
                                <a asp-area="" asp-controller="Appointments" asp-action="Create">Request An Appointment</a>
                            </h4>
                    </div>
                </div>

                <div class="col-link">
                    <div class="gift  bg-primary-blue center">
                        <a asp-area="" asp-controller="SendGifts" asp-action="Create" style="color:black;">
                            <i class="fas fa-gift fa-3x"></i>
                        </a>
                            <h4 class="center">
                                <a asp-area="" asp-controller="SendGifts" asp-action="Create">Gift</a>
                            </h4>
                    </div>
                    <div class="faq  bg-primary-blue center">
                        <a asp-area="" asp-controller="FAQ" asp-action="List" style="color:black;">
                            <i class="fas fa-question fa-3x"></i>
                        </a>
                            <h4 class="center">
                                <a asp-area="" asp-controller="FAQ" asp-action="List">FAQ</a>
                            </h4>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- main ends here-->
    <!-- News and event section-->
    <section class="news-event-box">
        <div class="news-box">
            <a asp-area="" asp-controller="NewsAndUpdate" asp-action="List">
                <h2 class="media-center">News</h2>
            </a>
            <div class="news-container">
                <div class="news-image">
                    <img src="~/images/News/abdominal-pain-2493327_1280.jpg" class="img-responsive"/>
                    
                    <div class="title-news">
                        <h4 class="center">New Title</h4>
                    </div>
                </div>
                <div class="news-image">
                   <img src="~/images/News/water1.jpg" class="img-responsive" />
                </div>
                    <div class="title-news">
                        <h4 class="center">News Title</h4>
                    </div>
                </div>
        </div>
</div>

        <div class="event-box">
            <a asp-area="" asp-controller="Event" asp-action="List">
                <h2>Event</h2>
            </a>
            <div class="event-container">
                <p class="event-text">
                    Contrary to popular belief, Lorem Ipsum is not simply random text.
                    It has roots in a piece of classical Latin literature from 45 BC,
                    making it over 2000 years old. Richard McClintock,
                    a Latin professor at Hampden-Sydney College in Virginia, looked up one
                    of the more obscure Latin words, consectetur, from a Lorem Ipsum passage,
                    and going through the cites of the word in classical literature,
                    discovered the undoubtable source. Lorem Ipsum comes from sections
                    1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil)
                    by Cicero, written in 45 BC. This book is a treatise on the theory of ethics,
                    very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor
                    sit amet..", comes from a line in section 1.10.32.

                    The standard chunk of Lorem Ipsum used since the 1500s is reproduced below
                    for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et
                    Malorum" by Cicero are also reproduced in their exact original form, accompanied by
                    English versions from the 1914 translation by H. Rackham.
                </p>
            </div>
        </div>
    </section>
    <!-- News and event section-->
                    <div class="patients-story">
                        <a asp-area="" asp-controller="Feedback" asp-action="List">  <h2>  Patient Story </h2></a>
                    </div>
                </div>
<!-- page-wrapper ends here-->