http5204-aspcore-group5-r2/Models/VisitorInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace http5204_aspcore_group5_r2.Models
{
    public class VisitorInformation
    {
        //for Visitor ID
        [Key]
        public int VisitorID { get; set; }

        //for VisitorName
        [Required, StringLength(255), Display(Name = "Name")]
        public string VisitorName { get; set; }

        //for Visiting Person Name(A Visitor visting a Person)
        [Required, StringLength(255), Display(Name = "Person Visiting")]
        public string VisitingPersonName { get; set; }

        //for Date Reference: https://stackoverflow.com/questions/43752832/format-date-within-view-in-asp-net-core-mvc
        //[Required, DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}"),Display(Name ="Date")]
        [Required, Display(Name = "Date")]
        public DateTime Date { get; set; }

        //for Time-In Reference: https://stackoverflow.com/questions/24549745/allow-only-hhmm-format-for-datetime-field-in-asp-net-mvc
        //This will be in /New (Page) When Visitor will be sign in 
        //[DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true),Display(Name ="Time-In")]
        //[DataType(DataType.Time)]
        [Display (Name = "TimeIn")]
        public DateTime TimeIn { get; set; }

        //for Time-Out 
        //This will be in Edit becuase after met when he will leaves
        //[DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true), Display(Name = "Time-Out")]
        //[DataType(DataType.Time)]
        [Display(Name = "TimeOut")]
        public DateTime? TimeOut { get; set; }

        //Visitor Information has Admin ID (Admin can create multiple VisitorInformations)
        [ForeignKey("AdminID")]
        public int AdminID { get; set; }

        public virtual Admin Admin { get; set; }
    }
}
 

http5204-aspcore-group5-r2/Controllers/VisitorInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using http5204_aspcore_group5_r2.Models;
//using http5204_aspcore_group5_r2.Models.ViewModelMargi;
using http5204_aspcore_group5_r2.Data;
using System.Diagnostics;

//Christine's Reference
namespace http5204_aspcore_group5_r2.Controllers
{
    public class VisitorInformationController : Controller
    {
        private readonly NDMHCMSContext db;

      
        private readonly UserManager<ApplicationUser> _userManager;

        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public VisitorInformationController(NDMHCMSContext context, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _userManager = usermanager;
        }


        /* public IActionResult Index()
         {
             return View();
         }
         */

        public async Task<int> GetUserDetails(ApplicationUser user)
        {
            //check if the user is an Admin or not.
            //UserState
            //0 => No User
            //1 => has user has no admin
            //2 => has user has admin but no VisitorInformations
            //3 => has user has admin and at least 1 VisitorInformation
            if (user == null) return 0;
            var userid = user.Id;
            if (user.AdminID == null) return 1;
            else
            {
                var uadminid = user.AdminID;
                var uservisitorinformations = await db.VisitorInformations.Where(v => v.AdminID == uadminid).ToListAsync();
                var uservisitorinfocount = uservisitorinformations.Count();
                if (uservisitorinfocount == 0) return 2;
                else if (uservisitorinfocount > 0) return 3;
            }
            return -1;//something went wrong
        }

        public async Task<bool> IsUserVisitorInformationsOwner(ApplicationUser user, int VisitorID)
        {
            if (user == null) return false;
            if (user.AdminID == null) return false;
           
            var uservisitorinfos = await
                db
                .VisitorInformations
                .Include(v => v.Admin)
                .Where(v => v.AdminID == user.AdminID)
                .Where(v => v.VisitorID == VisitorID)
                .ToListAsync();
            if (uservisitorinfos.Count() > 0) return true;
            return false;
        }

        //Index
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        //List
        /*  public ActionResult List()
          {
              List<VisitorInformation> visitorInformations = db.VisitorInformations.Include(v => v.Admin).ToList();

              return View(visitorInformations);
          } */

        public async Task<ActionResult> List(int pagenum)
        {
            //i added more functionality in visitor information /****/
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            //tell give us context about the user
            ViewData["UserState"] = userstate;
            ViewData["UserHasAdmin"] = 0; //default 0
            if (userstate == 3)
            {
                ViewData["UserHasAdmin"] = (int)user.AdminID;
            }

            //Pagination
            var listvisitorinformations = await db.VisitorInformations.Include(v => v.Admin).ToListAsync();
            int visitorinfocount = listvisitorinformations.Count();
            int perpage = 3;
            int maxpage = (int)Math.Ceiling((decimal)visitorinfocount / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }
            List<VisitorInformation> visitorinformations = await db.VisitorInformations.Include(v => v.Admin).Skip(start).Take(perpage).ToListAsync();


            //i added more functionality in visitor information /****/
            //var user = await GetCurrentUserAsync();
            //if (user != null)
            //{
            //    //if the user has no admin let the view know 
            //    if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
            //    //if the user has an admin then let the view know
            //    else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }
            //    return View(visitorinformations);
            //}
            //else
            //{
            //    //tell the view there is no admin
            //    ViewData["UserHasAdmin"] = "None";
            //    return View(visitorinformations);
            //}
            return View(visitorinformations);
        }

        

        public async Task<ActionResult> New()
        {
            
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
    
            switch (userstate)
            {
                case 0: return RedirectToAction("Register", "Account");
                case 1: return RedirectToAction("Create", "Admin");
            }
           
            ViewData["UserHasAdmin"] = user.AdminID;
           
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> New(string VisitorName_New, string VisitingPersonName_New, DateTime Date_New, DateTime TimeIn_New, int VisitorInfoAdmin_New)
        {
            
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);

           
            if (userstate < 2) return Forbid();
            if (user.AdminID != VisitorInfoAdmin_New)
            {
               
                return Forbid();
            }

            //for date 
            //DateTime da = DateTime.Now;
            //string Date = da.ToString("mm/dd/yyyy");
            //Raw Query   
            string query = "insert into visitorinformations (VisitorName, VisitingPersonName, Date, TimeIn, AdminID) values (@name, @visitingpersonname, @date, @timein, @admin)";

            SqlParameter[] myparams = new SqlParameter[5];
            //for @name paramter
            myparams[0] = new SqlParameter("@name", VisitorName_New);
            //for @visitingpersonname parameter
            myparams[1] = new SqlParameter("@visitingpersonname", VisitingPersonName_New);
            //for @date paramter 
            myparams[2] = new SqlParameter("@date", Date_New);// DateTime da = DateTime.Now; string date = da.ToString("dd/MM/YYYY");
                                                              //for @timein paramter 
            myparams[3] = new SqlParameter("@timein", TimeIn_New);
            //for @timeout paramter 
            //myparams[4] = new SqlParameter("@timeout", TimeOut_New);
            //for @admin (id) FOREIGN KEY paramter (AdminId Foreign Key)
            myparams[4] = new SqlParameter("@admin", VisitorInfoAdmin_New);

            
            db.Database.ExecuteSqlCommand(query, myparams);

           
            return RedirectToAction("List");
        }

      
        public async Task<ActionResult> Edit(int id)
        {

            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            bool isValid = await IsUserVisitorInformationsOwner(user, id);
            if (!isValid) return Forbid();


            var myvisitorinfo = db.VisitorInformations.Find(id); //finds that blog
            if (myvisitorinfo != null) return View(myvisitorinfo);
            else return NotFound();
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int id, string VisitorName, string VisitingPersonName, DateTime Date, DateTime TimeIn, DateTime TimeOut, int VisitorInfoAdmin)
        {
           
            if (db.VisitorInformations.Find(id) == null)
            {
                return NotFound();

            }

            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            if (userstate == 3)
            {
                bool isValid = await IsUserVisitorInformationsOwner(user, id);
                if (!isValid) return Forbid();
                //something is right

                //Raw Update MSSQL query
                string query = "update visitorinformations set VisitorName=@name, VisitingPersonName=@visitingpersonname, Date=@date, TimeIn=@timein, TimeOut=@timeout, AdminID=@admin where visitorid=@id";

                //[SqlParameter[] myparams] => SET variable myparams as an array of type (SqlParameter)
                //[new SqlParameter[1]] => Create a new SqlParameter array with 7 items
                SqlParameter[] myparams = new SqlParameter[7];
                //Parameter for @name "visitor name"
                myparams[0] = new SqlParameter("@name", VisitorName);
                //Parameter for @visitingpersonname "blogtitle"
                myparams[1] = new SqlParameter("@visitingpersonname", VisitingPersonName);
                //Parameter for @date "date"
                myparams[2] = new SqlParameter("@date", Date);
                //Parameter for @timein "timein"

http5204-aspcore-group5-r2/Views/VisitorInformation/Edit.cshtml
@model http5204_aspcore_group5_r2.Models.VisitorInformation
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form method="POST" action="/VisitorInformation/Edit/@Model.VisitorID">
    <!-- Foreign Key for Admin-->
    <div>
        <input type="hidden" id="VisitorInfoAdmin" name="VisitorInfoAdmin" value="@Model.AdminID" />
    </div>

    <!--Visitor Name-->
    <div>
        <label>Visitor Name:</label>
        <input type="text" value="@Model.VisitorName" id="VisitorName" name="VisitorName" />
    </div>

    <!--Visiting Person Name-->
    <div>
        <label>Visiting PersonName:</label>
        <input type="text" value="@Model.VisitingPersonName" id="VisitingPersonName" name="VisitingPersonName" />
    </div>

    <!--Date-->
    <div>
        <label>Date:</label>
        <input type="datetime" value="@Model.Date.ToShortDateString()" id="Date" name="Date" />
    </div>

    <!--Time In-->
    <div>
        <label>Time In:</label>
        <input type="datetime" value="@Model.TimeIn.ToShortTimeString()" id="TimeIn" name="TimeIn" />
    </div>

    <!--TimeOut Only in Edit View of Visitor Information-->
    <div>
        <label>TimeOut:</label>
        <input type="time" value="@Convert.ToDateTime(Model.TimeOut).ToShortTimeString()" id="TimeOut" name="TimeOut" />
    </div>

    <!--Submit Button-->
    <div>
        <input type="submit" value="Submit" />
    </div>

</form>

http5204-aspcore-group5-r2/Views/VisitorInformation/List.cshtml
@model IEnumerable<http5204_aspcore_group5_r2.Models.VisitorInformation>
@{
    ViewData["Title"] = "List";
}

<h2>Visitor Informations</h2>


<div class="page-wrapper">

    @{
        /*
        //UserState
            //0 => No User
            //1 => has user has no admin
            //2 => has user has admin but no visitor info
            //3 => has user has admin and at least 1 visitor info(post)
        */

        switch (ViewData["UserState"])
        {
            case 0:
                <div>
                <h3>Directions, Parking and Visiting Hours</h3>
                <p>Silent Hill Memorial Hospital is located in downtown Toronto just north of College Street and University Avenue.</p>
                <img src="~/images/siteImages/DirectionMapImage-VisitorInformation.jpg" alt="Map" style="width:400px;height:auto;" />

                <p>Visitig Hours</p>
                <p>
                    Family: 24 hours a day* <br />
                    Visitors: 10:00 a.m. – 9:00 p.m.
                </p>
                </div>

                break;


                case 1:
                <div>
                <h3>Directions, Parking and Visiting Hours</h3>
                <p>Silent Hill Memorial Hospital is located in downtown Toronto just north of College Street and University Avenue.</p>
                <img src="~/images/siteImages/DirectionMapImage-VisitorInformation.jpg" alt="Map" style="width:400px;height:auto;" />

                <p>Visitig Hours</p>
                <p>
                    Family: 24 hours a day* <br />
                    Visitors: 10:00 a.m. – 9:00 p.m.
                </p>
                </div>
                break;
        }
        }
  </div>


@*<div class="addbtn">
    <button>@Html.ActionLink("Add Visior Information", "New", "VisitorInformation")</button>
</div>*@

<div class="page-wrapper">

    <!--Pagination-->
    @*@ViewData["PaginationSummary"]
        @Html.ActionLink("Prev",
            "List",
            "VisitorInformation",
            new { pagenum= ((int)ViewData["pagenum"]-1)}
            )
        |
        @Html.ActionLink("Next",
            "List",
            "VisitorInformation",
            new { pagenum = ((int)ViewData["pagenum"] + 1) }
            )*@



    <!--Trying to Booetstrap-->
    <!--<table class="table">
        <thead>
            <tr>
                @*<th scope="col">No.</th>*@
                <th scope="col">Visitor Name</th>
                <th scope="col">Visiting Person Name</th>
                <th scope="col">Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var visitorinfo in Model)
            {
                <tr>
                    @*<th scope="row">@visitorinfo.VisitorID</th>*@
                    <td>@Html.ActionLink(visitorinfo.VisitorName, "Show/" + visitorinfo.VisitorID)</td>
                    @*<td>@visitorinfo.VisitorName</td>*@
                    <td>@visitorinfo.VisitingPersonName</td>
                    <td>@visitorinfo.Date.ToShortDateString()</td>
                </tr>
            }
        </tbody>
    </table>
        -->


    @{
        /*
        //UserState
            //0 => No User
            //1 => has user has no admin
            //2 => has user has admin but no faqs
            //3 => has user has admin and at least 1 faq(post)
        */

        switch (ViewData["UserState"])
        {//case 0: @Html.ActionLink("Sign Up!", "Register", "Account"); break;
         //case 1: @Html.ActionLink("Join Us", "Admin", "Create"); break;
            case 2:
                <button class="btn btn-primary">
                    @Html.ActionLink("Add Visior Information", "New", "VisitorInformation")
                </button>
                <div>


                    <!--Pagination-->
                    @ViewData["PaginationSummary"]
                    @Html.ActionLink("Prev",
                        "List",
                        "VisitorInformation",
                        new { pagenum= ((int)ViewData["pagenum"]-1)}
                        )
                    |
                    @Html.ActionLink("Next",
                        "List",
                        "VisitorInformation",
                        new { pagenum = ((int)ViewData["pagenum"] + 1) }
                        )


                    <table class="table">
                        <thead>
                            <tr>
                                @*<th scope="col">No.</th>*@
                                <th scope="col">Visitor Name</th>
                                <th scope="col">Visiting Person Name</th>
                                <th scope="col">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var visitorinfo in Model)
                            {
                                <tr>
                                    @*<th scope="row">@visitorinfo.VisitorID</th>*@
                                    <td>@Html.ActionLink(visitorinfo.VisitorName, "Show/" + visitorinfo.VisitorID)</td>
                                    @*<td>@visitorinfo.VisitorName</td>*@
                                    <td>@visitorinfo.VisitingPersonName</td>
                                    <td>@visitorinfo.Date.ToShortDateString()</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                break;



            case 3:
                <button class="btn btn-primary">
                    @Html.ActionLink("Add Visior Information", "New", "VisitorInformation")
                </button>

                <div>


                    <!--Pagination-->
                    @ViewData["PaginationSummary"]
                    @Html.ActionLink("Prev",
                        "List",
                        "VisitorInformation",
                        new { pagenum= ((int)ViewData["pagenum"]-1)}
                        )
                    |
                    @Html.ActionLink("Next",
                        "List",
                        "VisitorInformation",
                        new { pagenum = ((int)ViewData["pagenum"] + 1) }
                        )


                    <table class="table">
                        <thead>
                            <tr>
                                @*<th scope="col">No.</th>*@
                                <th scope="col">Visitor Name</th>
                                <th scope="col">Visiting Person Name</th>
                                <th scope="col">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var visitorinfo in Model)
                            {
                                <tr>
                                    @*<th scope="row">@visitorinfo.VisitorID</th>*@
                                    <td>@Html.ActionLink(visitorinfo.VisitorName, "Show/" + visitorinfo.VisitorID)</td>
                                    @*<td>@visitorinfo.VisitorName</td>*@
                                    <td>@visitorinfo.VisitingPersonName</td>
                                    <td>@visitorinfo.Date.ToShortDateString()</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                break;
        }

    }

</div>

http5204-aspcore-group5-r2/Views/VisitorInformation/New.cshtml
@{
    ViewData["Title"] = "New";
}

<h2>New</h2>

<form method="POST" action="/VisitorInformation/New">
    <!--For AdminID as a Foreign Key-->
    <div>
        <input type="hidden" id="VisitorInfoAdmin_New" name="VisitorInfoAdmin_New" value="@ViewData["UserHasAdmin"]" />
    </div>

    <!--For Visitor Name-->
    <div>
        <label>Visitor Name:</label>
        <input id="VisitorName_New" name="VisitorName_New" />
    </div>

    <!--Visiting Person Name-->
    <div>
        <label>Visiting Person Name:</label>
        <input id="VisitingPersonName_New" name="VisitingPersonName_New" />
    </div>

    <!--Date-->
    <div>
        <label>Date:</label>
        <input type="datetime" id="Date_New" name="Date_New" />
    </div>

    <!--Time In-->
    <div>
        <label>Time In:</label>
        <input type="time" id="TimeIn_New" name="TimeIn_New" />
    </div>

    <!--I  put Time Out In Edit View after a visitor visited a person(Patient)-->
    <!--Time Out will appear in Edit View because user admin will not know time out time when visitingperson will leave -->
    <!-- <div>
           <label>Time Out:</label>
           <input type="time" id="TimeOut_New" name="TimeOut_New" />
       </div>
        -->
    <!--Submit Button-->
    <div>
        <input type="submit" value="Submit" />
    </div>

</form>

http5204-aspcore-group5-r2/Views/VisitorInformation/Show.cshtml
@model http5204_aspcore_group5_r2.Models.VisitorInformation
@{
    ViewData["Title"] = "Show";
}

<h2>Show</h2>

<div class="box">
    <h3><label>Visitor Name:</label>@Model.VisitorName</h3>

    <p><label>Visiting Person Name:</label>@Model.VisitingPersonName</p>

    <p><label>Date:</label>@Model.Date.ToShortDateString()</p>

    <p><label>Time In:</label>@Model.TimeIn.ToShortTimeString()</p>

    <p><label>Time Out:</label>@Convert.ToDateTime(Model.TimeOut).ToShortTimeString()</p>

    <div>
        <div class="deletebtn">
            <button> @Html.ActionLink("Delete", "Delete/" + Model.VisitorID)</button>

        </div>
        <div class="editbtn">
            <button> @Html.ActionLink("Edit", "Edit/" + Model.VisitorID)</button>
        </div>
    </div>
</div>